name: Deploy to fly.io

on:
  push:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@main
        with:
          jvm: temurin@17
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build application
        run: ./mill show backend.assembly
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
